### ISSUE TITLE
Lazyload not working?  

### ISSUE THREAD

**Issue by daya0576** [theme-next/theme-next-jquery-lazyload#1]
# config
`/themes/next/_config.yml`:
```yml
# Added switch option for separated repo in 6.0.0.
# Dependencies: https://github.com/theme-next/theme-next-jquery-lazyload
lazyload: false
```

# result
all photos loaded immediately, lazyload not working:
![image](https://user-images.githubusercontent.com/6239652/45144623-376e2480-b1f1-11e8-89cc-57346b732c83.png)

**Comment by daya0576** [comment]
# Rendered images tag:
![image](https://user-images.githubusercontent.com/6239652/45144827-caa75a00-b1f1-11e8-8668-e36281ad932e.png)

**Comment by ivan-nginx** [comment]
https://theme-next.org/docs/tag-plugins/full-image/ – lazyload work in NexT site, but there is no Fancybox installed yet. Maybe some conflict with Fancybox?
